-- DDL Schema for MediClinicPro Supabase Migration (PostgreSQL)

-- Drop tables if exist (for clean initialization)
DROP TABLE IF EXISTS activity_logs CASCADE;
DROP TABLE IF EXISTS payments CASCADE;
DROP TABLE IF EXISTS lab_exams CASCADE;
DROP TABLE IF EXISTS prescription_items CASCADE;
DROP TABLE IF EXISTS prescriptions CASCADE;
DROP TABLE IF EXISTS stock_entries CASCADE;
DROP TABLE IF EXISTS medications CASCADE;
DROP TABLE IF EXISTS consultations CASCADE;
DROP TABLE IF EXISTS appointments CASCADE;
DROP TABLE IF EXISTS patients CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS clinics CASCADE;

-- 1. Clinics Table
CREATE TABLE clinics (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  address TEXT,
  phone TEXT,
  logo TEXT,
  subscription_status TEXT DEFAULT 'active', -- active, expired, trial
  subscription_expires_at TIMESTAMPTZ,
  settings JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Users Table
CREATE TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  clinic_id BIGINT REFERENCES clinics(id) ON DELETE CASCADE NOT NULL,
  name TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  role TEXT NOT NULL, -- admin, doctor, secretary, pharmacist, lab_tech, manager
  active INTEGER DEFAULT 1, -- 1=true, 0=false
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Patients Table
CREATE TABLE patients (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  clinic_id BIGINT REFERENCES clinics(id) ON DELETE CASCADE NOT NULL,
  folder_number TEXT UNIQUE NOT NULL, -- e.g. MED-2026-0001
  first_name TEXT NOT NULL,
  last_name TEXT NOT NULL,
  birth_date TEXT NOT NULL,
  gender TEXT NOT NULL, -- M, F
  phone TEXT NOT NULL,
  email TEXT,
  address TEXT,
  allergies TEXT DEFAULT '',
  antecedents TEXT DEFAULT '',
  archived INTEGER DEFAULT 0, -- 1=archived, 0=active
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Appointments Table
CREATE TABLE appointments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  clinic_id BIGINT REFERENCES clinics(id) ON DELETE CASCADE NOT NULL,
  patient_id BIGINT REFERENCES patients(id) ON DELETE CASCADE NOT NULL,
  practitioner_id BIGINT REFERENCES users(id) ON DELETE CASCADE NOT NULL, -- doctor user id
  date_time TEXT NOT NULL, -- ISO 8601 string
  duration INTEGER DEFAULT 30, -- minutes
  motif TEXT NOT NULL,
  status TEXT DEFAULT 'scheduled', -- scheduled, completed, cancelled
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Consultations Table
CREATE TABLE consultations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  clinic_id BIGINT REFERENCES clinics(id) ON DELETE CASCADE NOT NULL,
  patient_id BIGINT REFERENCES patients(id) ON DELETE CASCADE NOT NULL,
  doctor_id BIGINT REFERENCES users(id) ON DELETE CASCADE NOT NULL,
  date_time TIMESTAMPTZ DEFAULT NOW(),
  motif TEXT NOT NULL,
  symptoms TEXT,
  constants JSONB DEFAULT '{}'::jsonb, -- { tension: '', temp: '', weight: '', hr: '' }
  diagnosis TEXT,
  notes TEXT
);

-- 6. Medications Table
CREATE TABLE medications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  clinic_id BIGINT REFERENCES clinics(id) ON DELETE CASCADE NOT NULL,
  name TEXT NOT NULL,
  form TEXT NOT NULL,
  dosage TEXT NOT NULL,
  stock_quantity INTEGER DEFAULT 0,
  min_stock_threshold INTEGER DEFAULT 10,
  price_purchase REAL DEFAULT 0.0,
  price_sale REAL DEFAULT 0.0,
  expiry_date TEXT,
  batch_number TEXT,
  supplier TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. Stock Entries Table
CREATE TABLE stock_entries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  clinic_id BIGINT REFERENCES clinics(id) ON DELETE CASCADE NOT NULL,
  medication_id BIGINT REFERENCES medications(id) ON DELETE CASCADE NOT NULL,
  user_id BIGINT REFERENCES users(id) ON DELETE CASCADE NOT NULL,
  quantity INTEGER NOT NULL,
  price_purchase REAL NOT NULL,
  expiry_date TEXT,
  batch_number TEXT,
  supplier TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 8. Prescriptions Table
CREATE TABLE prescriptions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  clinic_id BIGINT REFERENCES clinics(id) ON DELETE CASCADE NOT NULL,
  consultation_id BIGINT UNIQUE REFERENCES consultations(id) ON DELETE CASCADE NOT NULL,
  patient_id BIGINT REFERENCES patients(id) ON DELETE CASCADE NOT NULL,
  doctor_id BIGINT REFERENCES users(id) ON DELETE CASCADE NOT NULL,
  date_time TIMESTAMPTZ DEFAULT NOW(),
  status TEXT DEFAULT 'pending' -- pending, dispensed, partial
);

-- 9. Prescription Items Table
CREATE TABLE prescription_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  prescription_id BIGINT REFERENCES prescriptions(id) ON DELETE CASCADE NOT NULL,
  medication_id BIGINT REFERENCES medications(id) ON DELETE SET NULL,
  medication_name TEXT NOT NULL,
  dosage TEXT,
  frequency TEXT,
  duration TEXT,
  quantity_prescribed INTEGER DEFAULT 1,
  quantity_dispensed INTEGER DEFAULT 0
);

-- 10. Laboratory Exams Table
CREATE TABLE lab_exams (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  clinic_id BIGINT REFERENCES clinics(id) ON DELETE CASCADE NOT NULL,
  consultation_id BIGINT REFERENCES consultations(id) ON DELETE SET NULL,
  patient_id BIGINT REFERENCES patients(id) ON DELETE CASCADE NOT NULL,
  doctor_id BIGINT REFERENCES users(id) ON DELETE CASCADE NOT NULL,
  test_name TEXT NOT NULL,
  status TEXT DEFAULT 'pending', -- pending, completed, cancelled
  results_text TEXT DEFAULT '',
  results_json JSONB DEFAULT '{}'::jsonb,
  technician_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  completed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 11. Payments Table
CREATE TABLE payments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  clinic_id BIGINT REFERENCES clinics(id) ON DELETE CASCADE NOT NULL,
  patient_id BIGINT REFERENCES patients(id) ON DELETE CASCADE NOT NULL,
  user_id BIGINT REFERENCES users(id) ON DELETE CASCADE NOT NULL, -- cashier user id
  amount_total REAL NOT NULL,
  payment_method TEXT NOT NULL, -- cash, wave, orange_money, mtn_momo
  reference_number TEXT,
  status TEXT DEFAULT 'paid',
  items JSONB NOT NULL, -- [{ type: 'consultation', name: 'Générale', cost: 10000 }]
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 12. Activity Logs Table
CREATE TABLE activity_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  clinic_id BIGINT REFERENCES clinics(id) ON DELETE CASCADE NOT NULL,
  user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  action TEXT NOT NULL,
  details TEXT,
  ip_address TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexing for rapid queries
CREATE INDEX idx_users_clinic ON users(clinic_id);
CREATE INDEX idx_patients_clinic ON patients(clinic_id);
CREATE INDEX idx_patients_search ON patients(last_name, first_name);
CREATE INDEX idx_appointments_clinic ON appointments(clinic_id);
CREATE INDEX idx_appointments_date ON appointments(date_time);
CREATE INDEX idx_medications_clinic ON medications(clinic_id);
CREATE INDEX idx_prescriptions_clinic ON prescriptions(clinic_id);
CREATE INDEX idx_lab_exams_clinic ON lab_exams(clinic_id);
CREATE INDEX idx_payments_clinic ON payments(clinic_id);
CREATE INDEX idx_activity_logs_clinic ON activity_logs(clinic_id);

-- SEED DATA FOR TESTING

-- Insert default clinic (expiring 1 year from now)
INSERT INTO clinics (id, name, address, phone, subscription_status, subscription_expires_at, settings) VALUES
(1, 'Clinique Médicale de l''Avenir', 'Cocody Boulevard de France, Abidjan, CI', '+225 0707080910', 'active', NOW() + INTERVAL '1 year', '{
  "tariffs": {
    "consultation_general": 10000,
    "consultation_specialist": 20000,
    "nfs": 5000,
    "malaria_test": 3000,
    "glycemia": 2000
  },
  "notifications": {
    "sms_reminders": true,
    "stock_alerts": true
  }
}');

-- Password hashes (bcrypt cost=10) - regenerated and verified against bcryptjs.compare()
INSERT INTO users (id, clinic_id, name, email, password_hash, role, active) VALUES
(1, 1, 'Administrateur', 'admin@mediclinic.com', '$2a$10$.xGSl.knQiHJcilqpOtTHe4MGzHSyZlM3GofsduMrbYs9PRv4eJ/S', 'admin', 1), -- adminpassword
(2, 1, 'Dr. Aminata Koné', 'aminata@mediclinic.com', '$2a$10$pzFlMyOI2De.LWBD.s96Guj/Sb6QiNJSjh6XBp5le1iaEy4k.6GLe', 'doctor', 1), -- doctorpassword
(3, 1, 'Dr. Ibrahim Traoré', 'ibrahim@mediclinic.com', '$2a$10$pzFlMyOI2De.LWBD.s96Guj/Sb6QiNJSjh6XBp5le1iaEy4k.6GLe', 'doctor', 1), -- doctorpassword
(4, 1, 'Koffi Bernard', 'bernard@mediclinic.com', '$2a$10$pqpzshRqNERXn6SxqO.OJOFQoq4tqqH/02igbXW47ZY/KoAH9.p36', 'secretary', 1), -- secretarypassword
(5, 1, 'Moussa Pharmacien', 'moussa@mediclinic.com', '$2a$10$N57s2TbUloU2fSjKxdh/7.w/GUjweOTtC0teKrNg7NxO1fivUlmZG', 'pharmacist', 1), -- pharmacistpassword
(6, 1, 'Fatou Laborantine', 'fatou@mediclinic.com', '$2a$10$ztStKuicP1UrLU57MIzIo.uqvxAyjKYYkbEsJ4MOH1g1Sn4xo/EKS', 'lab_tech', 1), -- labpassword
(7, 1, 'Kouassi Gestionnaire', 'kouassi@mediclinic.com', '$2a$10$1kZ1iuBuOROPMFY26C3SHONfVFCsuXHQJnJ9NRGfGW.UWEJDwA/72', 'manager', 1); -- managerpassword

-- Seed medications catalog
INSERT INTO medications (id, clinic_id, name, form, dosage, stock_quantity, min_stock_threshold, price_purchase, price_sale, expiry_date, batch_number, supplier) VALUES
(1, 1, 'Paracétamol', 'comprimé', '500mg', 150, 20, 500, 1000, '2027-12-31', 'B-PR-2026', 'PHARMA-CI'),
(2, 1, 'Amoxicilline', 'gélule', '500mg', 8, 10, 1200, 2500, '2026-09-15', 'B-AM-2026', 'MEDIC-AFRIQUE'),
(3, 1, 'Sirop Toux Enfant', 'sirop', '125ml', 45, 10, 800, 1800, '2026-08-10', 'B-TX-2026', 'PHARMA-CI'),
(4, 1, 'Ibuprofène', 'comprimé', '400mg', 80, 15, 600, 1200, '2028-06-30', 'B-IB-2026', 'MEDIC-AFRIQUE'),
(5, 1, 'Spasfon', 'comprimé', '80mg', 120, 10, 1000, 2000, '2027-04-30', 'B-SP-2026', 'PHARMA-CI');

-- Seed patients
INSERT INTO patients (id, clinic_id, folder_number, first_name, last_name, birth_date, gender, phone, email, address, allergies, antecedents) VALUES
(1, 1, 'MED-2026-0001', 'Koffi', 'Yao', '1988-04-12', 'M', '+225 0505123456', 'yao@gmail.com', 'Yopougon Selmer, Abidjan', 'Pénicilline', 'Hypertension'),
(2, 1, 'MED-2026-0002', 'Mariam', 'Diallo', '1995-11-23', 'F', '+225 0707987654', 'mariam@gmail.com', 'Cocody Angré, Abidjan', '', 'Diabète Type 2'),
(3, 1, 'MED-2026-0003', 'Jean-Baptiste', 'Kouamé', '1962-07-05', 'M', '+225 0101456789', 'jb@gmail.com', 'Marcory Zone 4, Abidjan', 'Aspirine', 'Insuffisance rénale');

-- Seed appointments (scheduled for today)
INSERT INTO appointments (id, clinic_id, patient_id, practitioner_id, date_time, duration, motif, status) VALUES
(1, 1, 1, 2, TO_CHAR(NOW(), 'YYYY-MM-DD') || 'T09:00:00', 30, 'Consultation générale - Fièvre', 'scheduled'),
(2, 1, 2, 2, TO_CHAR(NOW(), 'YYYY-MM-DD') || 'T10:30:00', 30, 'Suivi diabète', 'scheduled'),
(3, 1, 3, 3, TO_CHAR(NOW(), 'YYYY-MM-DD') || 'T14:00:00', 30, 'Bilan annuel', 'scheduled');

-- Reset sequences (PostgreSQL serial counter synchronization)
SELECT setval(pg_get_serial_sequence('clinics', 'id'), COALESCE(MAX(id), 1)) FROM clinics;
SELECT setval(pg_get_serial_sequence('users', 'id'), COALESCE(MAX(id), 1)) FROM users;
SELECT setval(pg_get_serial_sequence('patients', 'id'), COALESCE(MAX(id), 1)) FROM patients;
SELECT setval(pg_get_serial_sequence('appointments', 'id'), COALESCE(MAX(id), 1)) FROM appointments;
SELECT setval(pg_get_serial_sequence('medications', 'id'), COALESCE(MAX(id), 1)) FROM medications;
