import React, { useEffect, useState } from 'react';
import { api } from '../../../utils/api';
import { useNotifications } from '../../../contexts/NotificationContext';
import { SkeletonCards } from '../../../components/Skeleton';

type Tab = 'logins' | 'audit' | 'posture';

interface LoginsResponse {
  tableMissing: boolean;
  total24h: number;
  recent: { id: number; email: string; clinicId: number | null; reason: string; ip: string | null; createdAt: string }[];
  topIps: { ip: string; count: number; suspicious: boolean }[];
  topEmails: { email: string; count: number }[];
}

interface AuditResponse {
  rows: {
    id: number; clinicId: number; clinicName: string; userId: number | null; userName: string | null;
    action: string; details: string | null; ip: string | null; createdAt: string; isPlatformAction: boolean;
  }[];
  page: number;
  pageSize: number;
  hasMore: boolean;
  actions: string[];
}

interface PostureResponse {
  suspendedClinics: { id: number; name: string }[];
  clinicsWithoutActiveAdmin: { id: number; name: string }[];
  deactivatedUsers: number;
  googleOnlyAccounts: number;
  superAdminCount: number;
  rateLimitBackend: 'redis' | 'memory';
}

const REASON_LABELS: Record<string, string> = {
  unknown_or_inactive: 'Email inconnu ou compte désactivé',
  bad_password: 'Mot de passe incorrect'
};

const MIGRATION_SQL = `CREATE TABLE login_failures (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT NOT NULL,
  clinic_id BIGINT REFERENCES clinics(id) ON DELETE CASCADE,
  reason TEXT NOT NULL,
  ip_address TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);`;

const formatDate = (iso: string) => new Date(iso).toLocaleString('fr-FR');

const Row: React.FC<{ label: string; children: React.ReactNode }> = ({ label, children }) => (
  <div style={{
    display: 'flex', justifyContent: 'space-between', alignItems: 'center',
    padding: '9px 0', borderBottom: '1px solid var(--border)', gap: '12px'
  }}>
    <span style={{ fontSize: '0.85rem' }}>{label}</span>
    <span style={{ fontSize: '0.8rem', textAlign: 'right' }}>{children}</span>
  </div>
);

const Warn: React.FC<{ children: React.ReactNode }> = ({ children }) => (
  <p style={{
    fontSize: '0.8rem', color: 'hsl(0 65% 40%)', backgroundColor: 'hsl(0 70% 97%)',
    padding: '10px 12px', borderRadius: '8px', margin: '0 0 12px', lineHeight: 1.5
  }}>
    {children}
  </p>
);

export const SecuritySection: React.FC = () => {
  const { showToast } = useNotifications();
  const [tab, setTab] = useState<Tab>('logins');
  const [logins, setLogins] = useState<LoginsResponse | null>(null);
  const [audit, setAudit] = useState<AuditResponse | null>(null);
  const [posture, setPosture] = useState<PostureResponse | null>(null);
  const [loading, setLoading] = useState(true);
  const [auditAction, setAuditAction] = useState('');
  const [auditDays, setAuditDays] = useState(30);
  const [auditPage, setAuditPage] = useState(0);

  const loadAudit = async (action: string, days: number, page: number) => {
    const params = new URLSearchParams();
    if (action) params.set('action', action);
    params.set('days', String(days));
    params.set('page', String(page));
    setAudit(await api.get(`/platform/security/audit?${params.toString()}`));
  };

  useEffect(() => {
    (async () => {
      setLoading(true);
      try {
        const [loginsData, postureData] = await Promise.all([
          api.get('/platform/security/logins'),
          api.get('/platform/security/posture')
        ]);
        setLogins(loginsData);
        setPosture(postureData);
        await loadAudit('', 30, 0);
      } catch (err: any) {
        showToast('error', 'Erreur', err.error || 'Impossible de charger les données de sécurité.');
      } finally {
        setLoading(false);
      }
    })();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const applyAuditFilters = async (action: string, days: number, page: number) => {
    setAuditAction(action);
    setAuditDays(days);
    setAuditPage(page);
    try {
      await loadAudit(action, days, page);
    } catch (err: any) {
      showToast('error', 'Erreur', err.error || 'Impossible de charger le journal.');
    }
  };

  if (loading) return <SkeletonCards count={5} height={88} label="Chargement des données de sécurité…" />;

  const tabs: { id: Tab; label: string }[] = [
    { id: 'logins', label: 'Connexions' },
    { id: 'audit', label: "Journal d'audit" },
    { id: 'posture', label: 'Posture' }
  ];

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '16px' }}>
      <div style={{ display: 'flex', gap: '6px', flexWrap: 'wrap' }}>
        {tabs.map((item) => (
          <button
            key={item.id}
            type="button"
            className={tab === item.id ? 'btn btn-primary' : 'btn'}
            style={tab === item.id ? undefined : { border: '1px solid var(--border)' }}
            onClick={() => setTab(item.id)}
          >
            {item.label}
          </button>
        ))}
      </div>

      {tab === 'logins' && logins && (
        <>
          {logins.tableMissing ? (
            <div className="card">
              <Warn>
                La table <code>login_failures</code> est absente de la base : aucun échec de connexion n'est
                enregistré. La connexion fonctionne normalement, mais cette page reste vide tant que la
                migration n'est pas exécutée.
              </Warn>
              <pre style={{
                fontSize: '0.72rem', backgroundColor: 'var(--bg-primary)', padding: '12px',
                borderRadius: '8px', overflowX: 'auto', margin: 0
              }}>
                {MIGRATION_SQL}
              </pre>
            </div>
          ) : (
            <>
              <div className="card">
                <h3 style={{ margin: '0 0 8px', fontSize: '1rem' }}>Échecs de connexion</h3>
                <Row label="Sur les dernières 24 heures"><strong>{logins.total24h}</strong></Row>
              </div>

              <div className="card">
                <h3 style={{ margin: '0 0 4px', fontSize: '1rem' }}>Adresses IP les plus actives</h3>
                <p style={{ fontSize: '0.75rem', color: 'var(--text-muted)', margin: '0 0 8px' }}>
                  Une IP est signalée au-delà de 10 échecs dans la dernière heure. Le seuil porte sur l'heure
                  écoulée, pas sur le total : douze échecs étalés sur trois mois sont un utilisateur distrait.
                </p>
                {logins.topIps.length === 0 && (
                  <p style={{ fontSize: '0.85rem', color: 'var(--text-muted)' }}>Aucun échec enregistré.</p>
                )}
                {logins.topIps.map((entry) => (
                  <Row key={entry.ip} label={entry.ip}>
                    {entry.count} échec{entry.count > 1 ? 's' : ''}
                    {entry.suspicious && (
                      <span className="badge" style={{
                        marginLeft: '8px', backgroundColor: 'hsl(0 70% 95%)', color: 'hsl(0 65% 40%)'
                      }}>
                        Bourrage d'identifiants probable
                      </span>
                    )}
                  </Row>
                ))}
              </div>

              <div className="card">
                <h3 style={{ margin: '0 0 8px', fontSize: '1rem' }}>Comptes les plus visés</h3>
                {logins.topEmails.length === 0 && (
                  <p style={{ fontSize: '0.85rem', color: 'var(--text-muted)' }}>Aucun.</p>
                )}
                {logins.topEmails.map((entry) => (
                  <Row key={entry.email} label={entry.email}>{entry.count}</Row>
                ))}
              </div>

              <div className="card">
                <h3 style={{ margin: '0 0 8px', fontSize: '1rem' }}>Derniers échecs</h3>
                <div style={{ overflowX: 'auto' }}>
                  <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '0.8rem' }}>
                    <thead>
                      <tr style={{ textAlign: 'left', color: 'var(--text-muted)' }}>
                        <th style={{ padding: '6px 8px' }}>Date</th>
                        <th style={{ padding: '6px 8px' }}>Email visé</th>
                        <th style={{ padding: '6px 8px' }}>Motif</th>
                        <th style={{ padding: '6px 8px' }}>IP</th>
                      </tr>
                    </thead>
                    <tbody>
                      {logins.recent.map((row) => (
                        <tr key={row.id} style={{ borderTop: '1px solid var(--border)' }}>
                          <td style={{ padding: '6px 8px', whiteSpace: 'nowrap' }}>{formatDate(row.createdAt)}</td>
                          <td style={{ padding: '6px 8px' }}>{row.email}</td>
                          <td style={{ padding: '6px 8px' }}>{REASON_LABELS[row.reason] || row.reason}</td>
                          <td style={{ padding: '6px 8px' }}>{row.ip || '—'}</td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </div>
            </>
          )}
        </>
      )}

      {tab === 'audit' && audit && (
        <div className="card">
          <h3 style={{ margin: '0 0 8px', fontSize: '1rem' }}>Journal d'audit, toutes cliniques</h3>

          <div style={{ display: 'flex', gap: '10px', flexWrap: 'wrap', marginBottom: '12px' }}>
            <select
              className="input-control"
              style={{ maxWidth: '240px' }}
              value={auditAction}
              onChange={(e) => applyAuditFilters(e.target.value, auditDays, 0)}
            >
              <option value="">Toutes les actions</option>
              {audit.actions.map((action) => (
                <option key={action} value={action}>{action}</option>
              ))}
            </select>
            <select
              className="input-control"
              style={{ maxWidth: '160px' }}
              value={auditDays}
              onChange={(e) => applyAuditFilters(auditAction, parseInt(e.target.value, 10), 0)}
            >
              <option value={7}>7 derniers jours</option>
              <option value={30}>30 derniers jours</option>
              <option value={90}>90 derniers jours</option>
            </select>
          </div>

          <div style={{ overflowX: 'auto' }}>
            <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '0.8rem' }}>
              <thead>
                <tr style={{ textAlign: 'left', color: 'var(--text-muted)' }}>
                  <th style={{ padding: '6px 8px' }}>Date</th>
                  <th style={{ padding: '6px 8px' }}>Clinique</th>
                  <th style={{ padding: '6px 8px' }}>Auteur</th>
                  <th style={{ padding: '6px 8px' }}>Action</th>
                  <th style={{ padding: '6px 8px' }}>Détail</th>
                </tr>
              </thead>
              <tbody>
                {audit.rows.map((row) => (
                  <tr key={row.id} style={{ borderTop: '1px solid var(--border)' }}>
                    <td style={{ padding: '6px 8px', whiteSpace: 'nowrap' }}>{formatDate(row.createdAt)}</td>
                    <td style={{ padding: '6px 8px' }}>{row.clinicName}</td>
                    <td style={{ padding: '6px 8px' }}>{row.userName || '—'}</td>
                    <td style={{ padding: '6px 8px' }}>
                      {row.action}
                      {row.isPlatformAction && (
                        <span className="badge" style={{
                          marginLeft: '6px', backgroundColor: 'hsl(265 55% 95%)', color: 'hsl(265 55% 40%)'
                        }}>
                          Super Admin
                        </span>
                      )}
                    </td>
                    <td style={{ padding: '6px 8px' }}>{row.details || '—'}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          <div style={{ display: 'flex', gap: '8px', marginTop: '12px', alignItems: 'center' }}>
            <button
              type="button"
              className="btn"
              style={{ border: '1px solid var(--border)' }}
              disabled={auditPage === 0}
              onClick={() => applyAuditFilters(auditAction, auditDays, auditPage - 1)}
            >
              Précédent
            </button>
            <span style={{ fontSize: '0.8rem', color: 'var(--text-muted)' }}>Page {auditPage + 1}</span>
            <button
              type="button"
              className="btn"
              style={{ border: '1px solid var(--border)' }}
              disabled={!audit.hasMore}
              onClick={() => applyAuditFilters(auditAction, auditDays, auditPage + 1)}
            >
              Suivant
            </button>
          </div>
        </div>
      )}

      {tab === 'posture' && posture && (
        <>
          {posture.rateLimitBackend === 'memory' && (
            <div className="card">
              <Warn>
                La limitation de débit tourne en mémoire, pas sur Redis. En environnement serverless elle est
                donc par instance et remise à zéro à chaque démarrage à froid — la protection contre le
                bourrage d'identifiants est quasi inexistante. Renseignez UPSTASH_REDIS_REST_URL et
                UPSTASH_REDIS_REST_TOKEN.
              </Warn>
            </div>
          )}

          {posture.clinicsWithoutActiveAdmin.length > 0 && (
            <div className="card">
              <Warn>
                Ces cliniques n'ont plus aucun administrateur actif. Elles ne peuvent plus gérer leur
                personnel ni leur abonnement — elles sont enfermées dehors.
              </Warn>
              {posture.clinicsWithoutActiveAdmin.map((clinic) => (
                <Row key={clinic.id} label={clinic.name}>#{clinic.id}</Row>
              ))}
            </div>
          )}

          <div className="card">
            <h3 style={{ margin: '0 0 8px', fontSize: '1rem' }}>État des comptes</h3>
            <Row label="Cliniques suspendues par la plateforme">
              <strong>{posture.suspendedClinics.length}</strong>
            </Row>
            <Row label="Comptes désactivés"><strong>{posture.deactivatedUsers}</strong></Row>
            <Row label="Comptes Google sans mot de passe défini">
              <strong>{posture.googleOnlyAccounts}</strong>
            </Row>
            <Row label="Super Admins configurés"><strong>{posture.superAdminCount}</strong></Row>
            <Row label="Limitation de débit">
              {posture.rateLimitBackend === 'redis' ? 'Redis partagé' : 'Mémoire (par instance)'}
            </Row>
          </div>

          {posture.suspendedClinics.length > 0 && (
            <div className="card">
              <h3 style={{ margin: '0 0 8px', fontSize: '1rem' }}>Cliniques suspendues</h3>
              {posture.suspendedClinics.map((clinic) => (
                <Row key={clinic.id} label={clinic.name}>#{clinic.id}</Row>
              ))}
            </div>
          )}
        </>
      )}
    </div>
  );
};

export default SecuritySection;
